# Generated by Django 4.2.6 on 2023-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_clientuser_birthdate_clientuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pierre',
            name='couverture',
            field=models.ImageField(default='pierres/default.png', upload_to='pierres/'),
        ),
    ]
