# Generated by Django 4.2.6 on 2023-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_pierre_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pierre',
            name='couverture',
            field=models.ImageField(upload_to='pierres/'),
        ),
    ]
