# Generated by Django 4.2.6 on 2024-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_article_fk_prix_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
