# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
ServerRoot "/usr/local/apache2"

# Listen: Allows you to bind Apache to specific IP addresses and/or
# ports, instead of the default. See also the <VirtualHost>
Listen 80

# Dynamic Shared Object (DSO) Support
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule setenvif_module modules/mod_setenvif.so

# MPM
LoadModule mpm_event_module modules/mod_mpm_event.so

# Required modules for reverse proxy
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# 'Main' server configuration
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

# Custom log file locations
ErrorLog "/usr/local/apache2/logs/error.log"
LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog "/usr/local/apache2/logs/access.log" combined

# Virtual hosts
<VirtualHost *:80>
    ServerName lapierredelune.net
    
    # Error and Custom logs
    ErrorLog "/usr/local/apache2/logs/error.log"
    CustomLog "/usr/local/apache2/logs/access.log" combined

    # Proxying the connections to Gunicorn
    ProxyPreserveHost On
    ProxyPass / http://django:8000/
    ProxyPassReverse / http://django:8000/
</VirtualHost>

# Security settings
ServerTokens Prod
ServerSignature Off

# Specify a default charset for all content served
AddDefaultCharset UTF-8

# FileETag none is considered safer for privacy
FileETag None

# TraceEnable Off to enhance security by disallowing the TRACE method
TraceEnable Off
